{
  description = "Voting App";

  nixConfig = {
    extra-substituters = [ "https://scottylabs.cachix.org" ];
    extra-trusted-public-keys = [
      "scottylabs.cachix.org-1:hajjEX5SLi/Y7yYloiXTt2IOr3towcTGRhMh1vu6Tjg="
    ];
  };

  inputs = {
    nixpkgs.url = "github:cachix/devenv-nixpkgs/rolling";
    devenv.url = "github:cachix/devenv";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    treefmt-nix = {
      url = "github:numtide/treefmt-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    bun2nix = {
      url = "github:nix-community/bun2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, devenv, bun2nix, ... } @ inputs:
    let
      supportedSystems = [ "x86_64-linux" "aarch64-linux" "aarch64-darwin" "x86_64-darwin" ];
      forAllSystems = nixpkgs.lib.genAttrs supportedSystems;
      pkgsFor = system: nixpkgs.legacyPackages.${system};
    in
    {
      devShells = forAllSystems (system:
        let
          pkgs = pkgsFor system;
        in
        {
          # Devenv must resolve the real checkout (e.g. via git / PWD), not the flake copy in /nix/store,
          # or it will try to write `.devenv/` and SQLite caches under a read-only path.
          # Use: nix develop --no-pure-eval
          default = devenv.lib.mkShell {
            inherit inputs pkgs;
            modules = [ ./devenv.nix ];
          };
        });

      packages = forAllSystems (system:
        let
          pkgs = pkgsFor system;
        in
        {
          devenv = devenv.packages.${system}.devenv;
        }
        // (nixpkgs.lib.optionalAttrs (system == "x86_64-linux") (
          let
            b2n = bun2nix.packages.${system}.default;

            votingAppFrontend = b2n.mkDerivation {
              pname = "voting-app-frontend";
              version = (builtins.fromJSON (builtins.readFile ./frontend/package.json)).version;
              src = ./frontend;

              bunDeps = b2n.fetchBunDeps {
                bunNix = ./frontend/bun.nix;
              };

              buildPhase = ''
                nix flake update
                bun run build
              '';

              installPhase = ''
                mkdir -p $out
                cp -r dist/* $out/
              '';
            };

            # backend/Cargo.nix is generated by crate2nix; devenv pre-commit regenerates it when
            # backend/Cargo.toml or backend/Cargo.lock are staged (see git-hooks in devenv.nix).
            cargoNix = pkgs.callPackage ./backend/Cargo.nix { };

            votingAppBackend = cargoNix.workspaceMembers."backend".build;

          in
          {
            inherit votingAppFrontend votingAppBackend;
            default = votingAppBackend;
          }
        ))
      );
    };
}
