/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["auth_status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/motions/check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["check_motion"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/motions/create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_motion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/motions/end": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["end_motion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/motions/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["export_motion_results"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/motions/proxies": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_proxy_assignments"];
    put?: never;
    post: operations["assign_proxy"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/motions/results": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_motion_results"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/motions/vote": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["cast_vote"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/motions/vote-instances": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_vote_instances"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session/create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_session"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session/end": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["end_session"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session/join/{session_code}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["join_session"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session/lock": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["lock_session"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session/open": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["open_session"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["status_session"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session/{session_code}/attendance": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["attendance"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session/{session_code}/export/{kind}/{format}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["export_session_data"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session/{session_code}/motions/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["export_session_motions_json"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session/{session_code}/proxy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["set_session_proxy"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AssignProxyRequest: {
      /** Format: int32 */
      proxied_senator_user_id: number;
      /** Format: int32 */
      proxy_holder_user_id: number;
    };
    AssignProxyResponse: {
      /** Format: int32 */
      proxied_senator_user_id: number;
      /** Format: int32 */
      proxy_holder_user_id: number;
      /** Format: int32 */
      voter_instance_id: number;
    };
    AttendanceResponse: {
      attendees: components["schemas"]["AttendeeRecord"][];
      headcount: number;
      session_code: string;
    };
    AttendeeRecord: {
      andrew_id: string;
      /** Format: int32 */
      id: number;
      is_proxy_holder: boolean;
      name: string;
      proxy_for: string[];
    };
    AuthStatusResponse: {
      logged_in: boolean;
      user_andrew_id?: string | null;
      /** Format: int32 */
      user_id?: number | null;
      user_name?: string | null;
    };
    CastVoteRequest: {
      vote_response: string[];
      /** Format: int32 */
      voter_instance_id?: number | null;
    };
    CastVoteResponse: {
      /** Format: int32 */
      vote_id: number;
      /** Format: int32 */
      voter_instance_id: number;
    };
    CheckMotionActiveMotion: {
      data: Record<string, never>;
      /** Format: int32 */
      id: number;
      name: string;
    };
    CheckMotionResponse: {
      active_motion?: null | components["schemas"]["CheckMotionActiveMotion"];
    };
    CreateMotionRequest: {
      data?: Record<string, never> | null;
      /** Format: date-time */
      end_time?: string | null;
      name: string;
      /** Format: date-time */
      start_time?: string | null;
    };
    CreateMotionResponse: {
      /** Format: int32 */
      id: number;
      name: string;
      /** Format: date-time */
      start_time: string;
      status: components["schemas"]["StatusOption"];
    };
    CreateSessionResponse: {
      session_code: string;
    };
    EndMotionResponse: {
      /** Format: int32 */
      id: number;
      status: components["schemas"]["StatusOption"];
    };
    EndSessionResponse: {
      session_code: string;
      status: components["schemas"]["SessionStatus"];
    };
    MotionExportResponse: {
      /** Format: int32 */
      motion_id: number;
      motion_name: string;
      proxy_assignments: components["schemas"]["ProxyAssignment"][];
      totals: components["schemas"]["MotionResults"];
      votes: components["schemas"]["VoteExportRecord"][];
    };
    MotionOptionResult: {
      /** Format: int32 */
      count: number;
      label: string;
    };
    MotionResults: {
      options: components["schemas"]["MotionOptionResult"][];
      /** Format: int32 */
      total: number;
    };
    ProxyAssignment: {
      proxied_senator_name?: string | null;
      /** Format: int32 */
      proxied_senator_user_id: number;
      proxy_holder_name?: string | null;
      /** Format: int32 */
      proxy_holder_user_id: number;
      /** Format: int32 */
      voter_instance_id: number;
    };
    SessionInvolvement: {
      session_code: string;
      status: components["schemas"]["SessionStatus"];
    };
    SessionMotionExportItem: {
      end_time?: string | null;
      /** Format: int32 */
      motion_id: number;
      motion_name: string;
      option_counts: components["schemas"]["SessionMotionOptionCount"][];
      start_time: string;
      status: string;
      /** Format: int32 */
      total_votes: number;
    };
    SessionMotionOptionCount: {
      /** Format: int32 */
      count: number;
      option: string;
    };
    SessionMotionsExportResponse: {
      motions: components["schemas"]["SessionMotionExportItem"][];
      session_code: string;
      total_motions: number;
    };
    /** @enum {string} */
    SessionStatus: "Open" | "Locked" | "Closed";
    SetSessionProxyRequest: {
      is_senator: boolean;
      proxy_for?: string | null;
    };
    SetSessionProxyResponse: {
      has_proxy: boolean;
      is_senator: boolean;
      vote_instance_count: number;
    };
    /** @enum {string} */
    StatusOption: "Active" | "Inactive";
    StatusSessionResponse: {
      hosting?: null | components["schemas"]["SessionInvolvement"];
      in_session: boolean;
      participating?: null | components["schemas"]["SessionInvolvement"];
    };
    VoteExportRecord: {
      cast_time: string;
      is_proxy: boolean;
      proxied_senator_name?: string | null;
      /** Format: int32 */
      proxied_senator_user_id?: number | null;
      vote_response: string[];
      /** Format: int32 */
      voter_instance_id: number;
      voter_name?: string | null;
      /** Format: int32 */
      voter_user_id: number;
    };
    VoteInstance: {
      has_voted: boolean;
      is_proxy: boolean;
      proxy_for_name?: string | null;
      /** Format: int32 */
      proxy_for_user_id?: number | null;
      /** Format: int32 */
      voter_instance_id: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  auth_status: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current authentication status */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthStatusResponse"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
    };
  };
  check_motion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Active motion for the caller's session, or null */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckMotionResponse"];
        };
      };
      /** @description No active session */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_motion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMotionRequest"];
      };
    };
    responses: {
      /** @description Motion created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateMotionResponse"];
        };
      };
      /** @description Invalid proxy configuration */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Caller is not hosting an active session */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Session already has an active motion */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  end_motion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Motion ended (or already inactive) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EndMotionResponse"];
        };
      };
      /** @description Only the motion creator can end this motion */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No active hosted session or motion */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  export_motion_results: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Full motion export including votes and proxies */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MotionExportResponse"];
        };
      };
      /** @description Only the motion host may export results */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Motion not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_proxy_assignments: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Proxy assignments for the motion */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProxyAssignment"][];
        };
      };
      /** @description Only the motion host may view proxy assignments */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Motion not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  assign_proxy: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignProxyRequest"];
      };
    };
    responses: {
      /** @description Proxy assigned */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssignProxyResponse"];
        };
      };
      /** @description Invalid proxy assignment */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Only the motion host may assign proxies */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Motion not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Proxy already held or senator already proxied */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_motion_results: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Option counts for the motion */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MotionResults"];
        };
      };
      /** @description Results not yet available */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Motion not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  cast_vote: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CastVoteRequest"];
      };
    };
    responses: {
      /** @description Vote cast */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CastVoteResponse"];
        };
      };
      /** @description Invalid vote request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Motion not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Vote already cast for this instance */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_vote_instances: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Vote instances available to the current user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VoteInstance"][];
        };
      };
      /** @description Motion not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_session: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateSessionResponse"];
        };
      };
      /** @description Caller is already hosting an open or locked session */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  end_session: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session ended */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EndSessionResponse"];
        };
      };
      /** @description Caller is not hosting an active session */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  join_session: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Session join code */
        session_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Joined the session (or already joined) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Session is not open */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Session not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Caller is already participating in another active session */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  lock_session: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session locked */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EndSessionResponse"];
        };
      };
      /** @description Caller is not hosting an active session */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Session is not open */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  open_session: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session opened */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EndSessionResponse"];
        };
      };
      /** @description Caller is not hosting an active session */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Session is not locked */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  status_session: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Caller's current session involvement */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatusSessionResponse"];
        };
      };
    };
  };
  attendance: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Session join code */
        session_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Attendance list with proxy information */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AttendanceResponse"];
        };
      };
      /** @description Session not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  export_session_data: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Session join code */
        session_code: string;
        /** @description Export kind: attendance or vote */
        kind: string;
        /** @description Export format: pdf or csv */
        format: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Exported PDF or CSV attachment */
      200: {
        headers: {
          /** @description attachment; filename="{session_code}_{kind}.{pdf|csv}" */
          "Content-Disposition"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/pdf": number[];
          "text/csv": number[];
        };
      };
      /** @description Invalid kind or format */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  export_session_motions_json: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Session join code */
        session_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session motions export */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionMotionsExportResponse"];
        };
      };
      /** @description Only the session host may export motions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Session not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  set_session_proxy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Session join code */
        session_code: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetSessionProxyRequest"];
      };
    };
    responses: {
      /** @description Proxy / senator vote instances updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SetSessionProxyResponse"];
        };
      };
      /** @description Session is not open */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Session not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
