name: Backend CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: docker
    steps:
      - name: Checkout repository
        uses: https://data.forgejo.org/actions/checkout@v6

      - uses: https://github.com/dtolnay/rust-toolchain@stable
      - uses: https://github.com/Swatinem/rust-cache@v2

      - name: Run cargo check
        run: cargo check

  test:
    name: Test
    runs-on: docker
    steps:
      - name: Checkout repository
        uses: https://data.forgejo.org/actions/checkout@v6

      - uses: https://github.com/dtolnay/rust-toolchain@stable
      - uses: https://github.com/Swatinem/rust-cache@v2

      - name: Run cargo test
        run: cargo test

  format-and-lint:
    name: Format and Lint
    runs-on: docker
    steps:
      - name: Checkout repository
        uses: https://data.forgejo.org/actions/checkout@v6

      - uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: https://github.com/Swatinem/rust-cache@v2

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-features -- -D warnings
