name: Frontend CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check
    runs-on: docker
    container:
      image: denoland/deno:latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: https://data.forgejo.org/actions/checkout@v4

      - name: Install dependencies
        run: deno install

      - name: Check
        run: deno task check
