name: Frontend CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check
    runs-on: docker
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: https://data.forgejo.org/actions/checkout@v6

      - uses: https://github.com/denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Check
        run: deno task check
